# Site variables
title: Auth0 Prototypes
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://auth0-design-prototypes.surge.sh" # the base hostname & protocol for your site
html_description: "Jekyll site for prototyping Auth0 explorations"

# Build settings
highlighter: rouge
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

permalink: pretty 

collections:
  projects:
    output: true
    permalink: /work/:title/

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "portfolio"
      current_nav: "work"

exclude:
  - node_modules
  - assets
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js

include:
  - _pages

keep_files:
  - assets
